from tkinter import *
window = Tk()
l1 = Label(window, text="A label")
l1.grid(row=0, column=0)
l2 = Label(window, text="Another level")
l2.grid(row=1, column=0)
e1 = Entry(window)
e1.grid(row=0, column=1)
e2 = Entry(window)
e2.grid(row=1, column=1)
window.mainloop()

text = Label(window, text="Waz guud mah nibas")
submitButton = Button(window, text="Submit", fg="blue", bg="orange")
submitButton.config(width=20, height=20)
window.geometry('350x200')
text.pack()
submitButton.pack()
window.mainloop()
